parameters:
    mashery.api.class: AlexanderC\Api\Mashery\Mashery
    mashery.api.factory.class: AlexanderC\Api\Mashery\Mashery
    mashery.api.doctrine.sync_subscriber.class: AlexanderC\Api\MasheryBundle\EventListener\OrmSyncSubscriber

services:
    mashery.api:
        class: %mashery.api.class%
        factory_class: %mashery.api.factory.class%
        factory_method: createInstance
        arguments:
            - %mashery_api_api_key%
            - %mashery_api_secret%
            - %mashery_api_application%
            - %mashery_api_transport%
            - %mashery_api_version%

    mashery.api.doctrine.sync_subscriber:
        class: %mashery.api.doctrine.sync_subscriber.class%
        arguments: []
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: doctrine.event_subscriber, connection: default }